services:
  frankenphp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_frankenphp
    ports:
      - "8080:80"
      - "8443:443" 
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravelpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  pgdata:
